remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

title: Tech Trails
author: Arnaud Meersschaut
email: arnaudmeersschaut@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploring the world and online landscape.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meersschautarnaud.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
# twitter_username:   SBootstrap
github_username:      meersschautarnaud
# facebook_username:  
# instagram_username: 
linkedin_username:    arnaud-meersschaut-b17083155

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/work/_posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile.lock
